name: CI

on: push

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
          - name: Cloning repo
            uses: actions/checkout@v3

          - name: Setup Node.js environment
            uses: actions/setup-node@v3
            with:
                node-version: 18

          - name: Cache node_modules
            uses: actions/cache@v3
            with:
                path: "${{ github.workspace }}/node_modules"
                key: ${{ runner.os }}-lint-${{ hashFiles('package-lock.json', '*/package-lock.json') }}

          - name: Check for cached node_modules
            run: |
                if [ -d "${{ github.workspace }}/node_modules" ]; then
                    echo "Found cached node_modules, restoring from cache"
                else
                    echo "No cached node_modules found, installing dependencies"
                    npm ci
                fi

          - name: "Finally, CI"
            run: |
                npm run build:check && npm run lint
