name: Dokku

on:
    release:
        types: ["created"]
    workflow_dispatch:

jobs:
    ci:
        uses: "./.github/workflows/ci.yml"
        secrets: inherit

    dokku:
        runs-on: ubuntu-latest
        needs: [ci]
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
        steps:
            - name: Cloning repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build backend
              run: npm run backend:build

            - name: Allow /dist
              run: sed -i "s/dist\///g" .gitignore

            - name: Add and Commit
              uses: EndBug/add-and-commit@v9
              with:
                  push: false

            - name: Deploy to dokku
              uses: dokku/github-action@v1
              with:
                  git_push_flags: "--force"
                  git_remote_url: "ssh://dokku@${{ secrets.HOST }}:22/twopair"
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
