name: Release extension

on:
    workflow_dispatch:

jobs:
    ci:
        uses: "./.github/workflows/ci.yml"
        secrets: inherit

    release-ff:
        runs-on: ubuntu-latest
        needs: [ci]
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build prod bundle
              run: npm run extension:build:prod

            - name: Upload to AMO
              run: cd extension && npx -y web-ext-submit@7
              env:
                  WEB_EXT_API_KEY: ${{ secrets.FF_JWT_ISS }}
                  WEB_EXT_API_SECRET: ${{ secrets.FF_JWT_SECRET }}

    release-chrome:
        runs-on: ubuntu-latest
        needs: [ci]
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build prod bundle
              run: npm run extension:build:prod

            - name: Convert manifest to chrome
              run: |
                  "cd extension"
                  "jq '.background |= {worker_script: .scripts[0], type: .type}' manifest.json > _manifest.json"
                  "mv _manifest.json manifest.json"
                  "cat manifest.json"
